FROM almalinux:9
#CMD ["ping", "google.com"]
CMD ["yahoo.com"]
#ENTRYPOINT ["ping", "google.com"]
ENTRYPOINT ["ping"]


#CMD can be overriden at runtime but ENTRYPOINT can't be overriden at runtime
#when we are using ENTRYPOINT intruction, then CMD can provide argments to ENTRYPOINT
#So we can mention default argument through CMD and we can override them at runtime 