ARG version
FROM almalinux:${version:-9}
ARG course="DevOps with AWS" \
    duration="120 Hrs" 
RUN echo "Course: $course, duration: $duration, version: $version"
CMD ["sleep", "100"]


#ENV variables can reflect to image and container as well\
#